name: Deploy TicTacToe

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}    
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/apps/tic-tac-rustoe
            git fetch origin   
            git reset --hard origin/main
            source $HOME/.cargo/env  
            cargo build --release
            pm2 restart tictactoe-backend || pm2 start ./target/release/backend --name tictactoe-backend
            pm2 restart tictactoe-ws || pm2 start ./target/release/ws --name tictactoe-ws
            pm2 save